[package]
name = "axum-range"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "HTTP Range responses for axum"
homepage = "https://github.com/haileys/axum-range"
repository = "https://github.com/haileys/axum-range"
documentation = "https://docs.rs/axum-range"

[dependencies]
axum = { version = "0.6.20", default-features = false, features = ["headers"] }
bytes = "1.5.0"
futures = { version = "0.3.28", default-features = false, features = ["std"] }
pin-project = "1.1.3"
tokio = { version = "1.32.0", features = ["fs", "io-util"] }

[dev-dependencies]
assert_matches = "1.5"
tokio = { version = "*", features = ["rt", "macros"] }
